version: 2.1

jobs:
  test:
    docker:
      - image: sergiomesasyelamos2000/cc-proyecto-22-23:latest
    steps:
      - checkout
      - run: docker run sergiomesasyelamos2000/cc-proyecto-22-23:latest

workflows:
  test_project:
    jobs:
      - test
 