version: 2.1

jobs:
  test:
    docker:
      - image: sergiomesasyelamos2000/cc-proyecto-22-23:latest
    steps:
      - checkout
      - run: npm rm -rf node_modules && rm package.json
      - run: npm install
      - run: npm run test

workflows:
  test_project:
    jobs:
      - test
 