version: 2.1
orbs:
  node: circleci/node@4.7.0
jobs:
  test:
    docker:
      - image: sergiomesasyelamos2000/cc-proyecto-22-23:latest
    steps:
      - checkout:
          path: /root/project/backend
      - run:
          name: Running container
          command: npm run test1
workflows:
  test_my_app:
    jobs:
      - test
 