version: 2.1 
jobs:
  build:
    docker:
      - image: sergiomesasyelamos2000/cc-proyecto-22-23:latest
    steps:
      - checkout
      - run:
          name: Running container
workflows:
  test_my_app:
    jobs:
      - build
 