version: 2.1

jobs:
  test:
    docker:
      - image: sergiomesasyelamos2000/cc-proyecto-22-23:latest
    steps:
      - checkout
       name: Running tests
      - run: cd backend && npm install --save && npm run test

workflows:
  test_project:
    jobs:
      - test
 