version: 2.1
orbs:
  node: circleci/node@4.7.0
jobs:
  test:
    docker:
      - image: sergiomesasyelamos2000/cc-proyecto-22-23:latest
    working_directory: /root/project/backend
    steps:
      - checkout
      - run: sudo npm run jest --verbose
      
workflows:
  test_my_app:
    jobs:
      - test
 