version: 2.1

jobs:
  test:
    docker:
      - image: sergiomesasyelamos2000/cc-proyecto-22-23:latest
    steps:
      - checkout
      - run: npm rm -rf node_modules
      - run: cd backend
      - run: ls -l
      - run: npm install --save
      - run: npm run test

workflows:
  test_project:
    jobs:
      - test
 