name: Run Tests

on:
  push:
    branches: [ main ]

jobs:
  run_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lanzar Tests CI
        run:
          docker run -t -v `pwd`:/app/test sergiomesasyelamos2000/cc-proyecto-22-23