name: Run Tests

on:
  push:
    branches: [main]
  workflow_run:
    workflows: ["GitHub Container Registry"]
    types:
      - completed

jobs:
  run_test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - name: Lanzar Tests CI
        run:
          docker run -t -v `pwd`:/app/test sergiomesasyelamos2000/cc-proyecto-22-23